version: '3'
services:
  vue:
    build: .
    container_name: vue-container
    hostname: vue-container
    tty: true
    volumes:
      - ./app:/root/app
      - ./scripts:/root/scripts
    ports:
      - "9000:9000"
